version: '3.1'
services:
  API:
    image: 'stc-assessment'
    container_name: stc-assessment-container
    ports:
      - "8080:8080"
    depends_on:
      PostgreSQL:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/stc_assissment
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456789
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  PostgreSQL:
    image: postgres-image
    container_name: postgres-image-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stc_assissment
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5